//
//  HistoryPartnerDetailCheckoutPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/20/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailCheckoutPresenter: HistoryPartnerDetailCheckoutPresenterProtocol, HistoryPartnerDetailCheckoutInteractorOutputProtocol {

    weak private var view: HistoryPartnerDetailCheckoutViewProtocol?
    var interactor: HistoryPartnerDetailCheckoutInteractorInputProtocol?
    private let router: HistoryPartnerDetailCheckoutWireframeProtocol

    init(interface: HistoryPartnerDetailCheckoutViewProtocol, interactor: HistoryPartnerDetailCheckoutInteractorInputProtocol?, router: HistoryPartnerDetailCheckoutWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getCheckoutDetail(bookingID: String, parkingID: String) {
        ProgressView.shared.showProgressOnWindow()
        Provider.shared.parkingAPIService.getHistoryParkingDetail(parkingID: parkingID, bookingID: bookingID, success: { (historyDetail) in
            ProgressView.shared.hide()
            self.view?.didGetCheckoutDetail(historyDetail: historyDetail)
        }) { (_) in
            ProgressView.shared.hide()
        }
    }

}
