//
//  HistoryPartnerDetailBookingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailBookingPresenter: HistoryPartnerDetailBookingPresenterProtocol, HistoryPartnerDetailBookingInteractorOutputProtocol {

    weak private var view: HistoryPartnerDetailBookingViewProtocol?
    var interactor: HistoryPartnerDetailBookingInteractorInputProtocol?
    private let router: HistoryPartnerDetailBookingWireframeProtocol

    init(interface: HistoryPartnerDetailBookingViewProtocol, interactor: HistoryPartnerDetailBookingInteractorInputProtocol?, router: HistoryPartnerDetailBookingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getHistoryParkingDetailBooking(parkingID: String, bookingID: String) {
        ProgressView.shared.showProgressOnWindow()
        Provider.shared.parkingAPIService.getHistoryParkingDetail(parkingID: parkingID, bookingID: bookingID, success: { (historyParkingDetail) in
            ProgressView.shared.hide()
            self.view?.didGetData(historyPakingDetail: historyParkingDetail)
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
