//
//  HistoryPartnerDetailBookingProtocols.swift
//  EcoPark
//
//  Created Tu DV on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryPartnerDetailBookingWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPartnerDetailBookingPresenterProtocol: class {

    var interactor: HistoryPartnerDetailBookingInteractorInputProtocol? { get set }
    func getHistoryParkingDetailBooking(parkingID: String, bookingID: String)

}

//MARK: Interactor -
protocol HistoryPartnerDetailBookingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HistoryPartnerDetailBookingInteractorInputProtocol: class {

    var presenter: HistoryPartnerDetailBookingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryPartnerDetailBookingViewProtocol: class {

    var presenter: HistoryPartnerDetailBookingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetData(historyPakingDetail: HistoryBookingParkingResponse?)

}
