//
//  HistoryPartnerDetailBookingInteractor.swift
//  EcoPark
//
//  Created Tu DV on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailBookingInteractor: HistoryPartnerDetailBookingInteractorInputProtocol {

    weak var presenter: HistoryPartnerDetailBookingInteractorOutputProtocol?
}
