//
//  ParkingInfoInteractor.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingInfoInteractor: ParkingInfoInteractorInputProtocol {

    weak var presenter: ParkingInfoInteractorOutputProtocol?
}
