//
//  WalletProtocols.swift
//  EcoPark
//
//  Created Ngoc Duong on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WalletWireframeProtocol: class {

}
//MARK: Presenter -
protocol WalletPresenterProtocol: class {

    var interactor: WalletInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol WalletInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol WalletInteractorInputProtocol: class {

    var presenter: WalletInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol WalletViewProtocol: class {

    var presenter: WalletPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
