//
//  WalletPresenter.swift
//  EcoPark
//
//  Created Ngoc Duong on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WalletPresenter: WalletPresenterProtocol, WalletInteractorOutputProtocol {

    weak private var view: WalletViewProtocol?
    var interactor: WalletInteractorInputProtocol?
    private let router: WalletWireframeProtocol

    init(interface: WalletViewProtocol, interactor: WalletInteractorInputProtocol?, router: WalletWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
