//
//  WalletInteractor.swift
//  EcoPark
//
//  Created Ngoc Duong on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WalletInteractor: WalletInteractorInputProtocol {

    weak var presenter: WalletInteractorOutputProtocol?
}
