//
//  MyNotificationViewController.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class MyNotificationViewController: ListManagerVC, MyNotificationViewProtocol {
   
	var presenter: MyNotificationPresenterProtocol?
    
    var notification: [NotificationEntity] = [] {
        didSet {
            self.tableView.reloadData()
        }
    }
    
    override func setUpViews() {
        super.setUpViews()
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.initLoadData(data: Array(repeating: 1, count: self.notification.count))
        }
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        presenter?.getNotification(screen: "notification", offset: 0, limit: limitLoad)
    }
    
    override func registerTableView() {
        super.registerTableView()
        self.tableView.registerXibFile(NotificationCell.self)
        self.view.backgroundColor = .clear

    }
    
    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = self.tableView.dequeue(NotificationCell.self, for: indexPath)
        if indexPath.item < notification.count {
            let status = notification[indexPath.item].isRead
            var statusType: NotificationStatus = .UnRead
            if status ?? false {
                statusType = NotificationStatus.IsRead
            } else {
                statusType = NotificationStatus.UnRead
            }
            let dateTime = notification[indexPath.item].createTime?.toString(dateFormat: .HHmmddMMyyyy)
            let content = notification[indexPath.item].content
            
            cell.displayData(type: .MyNotification, status: statusType , datetime: dateTime&, content: content&)
        }
        
       
        return cell
    }
    
    override func didSelectTableView(item: Any, indexPath: IndexPath) {
        guard let actionKey = notification[indexPath.item].actionKey, let id =  notification[indexPath.item].id else { return }
        let bookingID = notification[indexPath.item].bookingID
        let parkingID = UserDefaultHelper.shared.parkingID
        presenter?.getNotificationDetail(notificationID: Int(id) ?? 0)
        switch actionKey {
        case NotificationKey.NOTIF_CHECK_TIME_OUT.rawValue, NotificationKey.NOTIF_BOOKING_EXPIRED_FOR_CUS.rawValue, NotificationKey.NOTIF_CHECK_TIME_END_PARKING.rawValue, NotificationKey.NOTIF_RATING_FOR_CUSTOMER.rawValue, NotificationKey.NOTIF_CHECK_INTEND_CHEKCIN_TIME.rawValue, NotificationKey.NOTIF_CHECKED_OUT.rawValue:
            let vc = DetailParkingRouter.createModule(bookingID: bookingID ?? "")
            self.push(controller: vc)
        case NotificationKey.NOTIF_BOOKING_EXPIRED_FOR_BOSS.rawValue, NotificationKey.NOTIF_RATING_FOR_BOSS_PARKING.rawValue, NotificationKey.NOTIF_STATUS_CANCEL.rawValue:
            let vc = HistoryPartnerDetailCheckoutRouter.createModule(bookingID: bookingID ?? "", parkingID: parkingID)
            vc.isFromList = true
            self.push(controller: vc)
        case NotificationKey.THE_WALLET_RUNS_OUT_OF_MONEY.rawValue, NotificationKey.NOTIF_PLUS.rawValue, NotificationKey.NOTIF_PLUS_MONEY_FOR_BOSS.rawValue:
            let vc = WalletRouter.createModule()
            vc.isBack = true
            self.push(controller: vc)
        case NotificationKey.NOTIF_REGISTER_BOSS_PARKING.rawValue:
            let vc = ParkingInfoRouter.createModule()
            self.push(controller: vc)
        case NotificationKey.NOTIF_EXTRA.rawValue, NotificationKey.NOTIF_CHECKIN_EARLY.rawValue:
            let vc = HistoryPartnerDetailCheckinRouter.createModule(parkingID: parkingID, bookingID: bookingID ?? "")
            vc.isNoti = true
            self.push(controller: vc)
        case NotificationKey.NOTIF_BOOKING_FOR_BOSS.rawValue:
            let vc = HistoryPartnerDetailBookingRouter.createModule(parkingID: parkingID, bookingID: bookingID ?? "")
            self.push(controller: vc)
        default:
            break
        }
    }
    
    func didGetNotification(notification: ParentNotificationEntity?) {
        let noti = notification?.notifications
        guard let notiSystem = (noti?.filter({ (notification) -> Bool in
            notification.screen == "NOTIFICATION"
        })) else { return }
        self.notification = notiSystem
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.initLoadData(data: Array(repeating: 1, count: self.notification.count ))
        }
    }
}

extension MyNotificationViewController: IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.Giveme.showLanguage)
    }
}
