//
//  MyNotificationProtocols.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MyNotificationWireframeProtocol: class {

}
//MARK: Presenter -
protocol MyNotificationPresenterProtocol: class {

    var interactor: MyNotificationInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MyNotificationInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MyNotificationInteractorInputProtocol: class {

    var presenter: MyNotificationInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MyNotificationViewProtocol: class {

    var presenter: MyNotificationPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
