//
//  HomeFindViewController.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/26/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeFindViewController: BaseViewController, HomeFindViewProtocol {

	var presenter: HomeFindPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
