//
//  HomeFindPresenter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/26/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeFindPresenter: HomeFindPresenterProtocol, HomeFindInteractorOutputProtocol {

    weak private var view: HomeFindViewProtocol?
    var interactor: HomeFindInteractorInputProtocol?
    private let router: HomeFindWireframeProtocol

    init(interface: HomeFindViewProtocol, interactor: HomeFindInteractorInputProtocol?, router: HomeFindWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
