//
//  LoginInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/9/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor: LoginInteractorInputProtocol {

    weak var presenter: LoginInteractorOutputProtocol?
    
    func login(username: String, password: String) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.login(username: username, password: password, success: { (user) in
            //save user
            ProgressView.shared.hide()
            
            guard let user = user else { return }
            UserDefaultHelper.shared.saveUser(user: user)
            UserDefaultHelper.shared.userToken = user.jwt&
            UserDefaultHelper.shared.birthday = user.birthDay

            // --
            self.presenter?.didLogin(user: user)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.didLogin(error: error)
        }
    }
    
    func loginSocial(param: LoginSocialParam) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.loginGmail(param: param, success: { user in
            ProgressView.shared.hide()
            guard let user = user else { return }
            UserDefaultHelper.shared.saveUser(user: user)
            UserDefaultHelper.shared.userToken = user.jwt&
            UserDefaultHelper.shared.birthday = user.birthDay
            self.presenter?.didLogin(user: user)
        }) { error in
            ProgressView.shared.hide()
            self.presenter?.didLogin(error: error)
        }
    }
}
