//
//  SignUpPartnerStep1Interactor.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep1Interactor: SignUpPartnerStep1InteractorInputProtocol {

    weak var presenter: SignUpPartnerStep1InteractorOutputProtocol?
}
