//
//  SignUpPartnerStep1Protocols.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpPartnerStep1WireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPartnerStep1PresenterProtocol: class {

    var interactor: SignUpPartnerStep1InteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SignUpPartnerStep1InteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignUpPartnerStep1InteractorInputProtocol: class {

    var presenter: SignUpPartnerStep1InteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignUpPartnerStep1ViewProtocol: class {

    var presenter: SignUpPartnerStep1PresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
