//
//  HistoryPartnerProtocols.swift
//  EcoPark
//
//  Created Tu DV on 11/4/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryPartnerWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPartnerPresenterProtocol: class {

    var interactor: HistoryPartnerInteractorInputProtocol? { get set }
    func getHistoryParking(parkingID: String, status: String, keyword: String)
}

//MARK: Interactor -
protocol HistoryPartnerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HistoryPartnerInteractorInputProtocol: class {

    var presenter: HistoryPartnerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryPartnerViewProtocol: class {

    var presenter: HistoryPartnerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetHistoryParking(historyParking: HistoryMyParkingEntity?)
}
