//
//  HistoryPartnerInteractor.swift
//  EcoPark
//
//  Created Tu DV on 11/4/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerInteractor: HistoryPartnerInteractorInputProtocol {

    weak var presenter: HistoryPartnerInteractorOutputProtocol?
}
