//
//  HistoryPartnerBookingViewController.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class HistoryPartnerBookingViewController: BaseViewController {

    @IBOutlet weak var vSearch: AppSearchBar!
    @IBOutlet weak var tbBooking: UITableView!
    
	var presenter: HistoryPartnerBookingPresenterProtocol?

    var bookingReservation: Int = 0
    var historyParkingBooking: HistoryMyParkingEntity? {
        didSet {
            tbBooking.reloadData()
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        configTableView()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        getData()
    }
    
    override func setUpViews() {
        super.setUpViews()
        vSearch.setTitleAndPlaceHolder(icon: nil, placeHolder: LocalizableKey.searchNumberCar.showLanguage)
        vSearch.actionSearch = { text in
            var parkingID = UserDefaultHelper.shared.loginUserInfo?.infoParking?.id
            if parkingID == "" || parkingID == nil {
                parkingID = UserDefaultHelper.shared.loginUserInfo?.parkingID
            }
            self.presenter?.getHistoryParkingBooking(parkingID: parkingID&, status: "checked_in", keyword: text)
        }
        vSearch.tapToTextField = {
            let text = self.vSearch.tfInput.text!
            print(text)
            var parkingID = UserDefaultHelper.shared.loginUserInfo?.infoParking?.id
            if parkingID == "" || parkingID == nil {
                parkingID = UserDefaultHelper.shared.loginUserInfo?.parkingID
            }
            self.presenter?.getHistoryParkingBooking(parkingID: parkingID&, status: "reservation", keyword: text)
        }
    }
    
    private func getData() {
        var parkingID = UserDefaultHelper.shared.loginUserInfo?.infoParking?.id
        if parkingID == "" || parkingID == nil {
            parkingID = UserDefaultHelper.shared.loginUserInfo?.parkingID
        }
        presenter?.getHistoryParkingBooking(parkingID: parkingID&, status: "reservation", keyword: "")
    }
}

extension HistoryPartnerBookingViewController: UITableViewDataSource, UITableViewDelegate {
    
    func configTableView() {
        tbBooking.delegate = self
        tbBooking.dataSource = self
        tbBooking.separatorStyle = .none
        tbBooking.registerXibFile(HistoryParnerCell.self)
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return historyParkingBooking?.booking.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(HistoryParnerCell.self)
        cell.setDataBookingHistory()
        cell.setDataHistory(historyParking: historyParkingBooking?.booking[indexPath.item])
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        self.push(controller: HistoryPartnerDetailBookingRouter.createModule(parkingID: historyParkingBooking?.booking[indexPath.item].parking_id ?? "", bookingID: historyParkingBooking?.booking[indexPath.item].id ?? ""))
    }
}

extension HistoryPartnerBookingViewController: IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.booked.showLanguage + " (\(bookingReservation))")
    }
}

extension HistoryPartnerBookingViewController: HistoryPartnerBookingViewProtocol {
    func didGetHistoryParkingBooking(historyParking: HistoryMyParkingEntity?) {
        self.historyParkingBooking = historyParking
    }
    
}
