//
//  HistoryPartnerBookingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerBookingPresenter: HistoryPartnerBookingPresenterProtocol, HistoryPartnerBookingInteractorOutputProtocol {

    weak private var view: HistoryPartnerBookingViewProtocol?
    var interactor: HistoryPartnerBookingInteractorInputProtocol?
    private let router: HistoryPartnerBookingWireframeProtocol

    init(interface: HistoryPartnerBookingViewProtocol, interactor: HistoryPartnerBookingInteractorInputProtocol?, router: HistoryPartnerBookingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func getHistoryParkingBooking(parkingID: String, status: String, keyword: String, offset: Int, limit: Int) {
        ProgressView.shared.showProgressOnWindow()
        Provider.shared.parkingAPIService.getHistoryMyParking(parkingID: parkingID, status: status, keyword: keyword, offset: offset, limit: limit, success: { (historyParking) in
            ProgressView.shared.hide()
            self.view?.didGetHistoryParkingBooking(historyParking: historyParking)
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
