//
//  HistoryPartnerBookingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerBookingPresenter: HistoryPartnerBookingPresenterProtocol, HistoryPartnerBookingInteractorOutputProtocol {

    weak private var view: HistoryPartnerBookingViewProtocol?
    var interactor: HistoryPartnerBookingInteractorInputProtocol?
    private let router: HistoryPartnerBookingWireframeProtocol

    init(interface: HistoryPartnerBookingViewProtocol, interactor: HistoryPartnerBookingInteractorInputProtocol?, router: HistoryPartnerBookingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
