//
//  SignUpPartnerStep1ViewController.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep1ViewController: BaseViewController, SignUpPartnerStep1ViewProtocol {

    @IBOutlet weak var lbPartnerInfo: UILabel!
    @IBOutlet  weak var vPartnerName: AppTextField!
    @IBOutlet weak var vGender: AppDropDown!
    @IBOutlet weak var vBirthday: AppDateDropDown!
    @IBOutlet weak var vIDNumber: AppTextField!
    @IBOutlet weak var vIssuedBy: AppDropDown!
    @IBOutlet weak var vDateBy: AppDateDropDown!
    @IBOutlet weak var vEmail: AppTextField!
    @IBOutlet weak var lbImage: UILabel!
    @IBOutlet weak var btnNext: UIButton!
    
	var presenter: SignUpPartnerStep1PresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }

    private func setupUI() {
        lbPartnerInfo.text = LocalizableKey.parnerInfo.showLanguage
        vPartnerName.setTitleAndPlaceHolder(title: LocalizableKey.partnerName.showLanguage, placeHolder: LocalizableKey.enter.showLanguage)
        vGender.setTitleAndPlaceHolder(title: LocalizableKey.gender.showLanguage, placeHolder: LocalizableKey.select.showLanguage)
        vBirthday.setTitleAndPlaceHolder(title: LocalizableKey.birthday.showLanguage, placeHolder: LocalizableKey.select.showLanguage)
        vIDNumber.setTitleAndPlaceHolder(title: LocalizableKey.partnerID.showLanguage, placeHolder: LocalizableKey.enter.showLanguage)
        vIssuedBy.setTitleAndPlaceHolder(title: LocalizableKey.issuedBy.showLanguage, placeHolder: LocalizableKey.select.showLanguage)
        vDateBy.setTitleAndPlaceHolder(title: LocalizableKey.dayBy.showLanguage, placeHolder: LocalizableKey.select.showLanguage)
        vEmail.setTitleAndPlaceHolder(title: LocalizableKey.partnerEmail.showLanguage, placeHolder: LocalizableKey.enter.showLanguage)
        lbImage.text = LocalizableKey.partnerImage.showLanguage
    }
    
}
