//
//  SignUpPartnerStep1Router.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep1Router: SignUpPartnerStep1WireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignUpPartnerStep1ViewController(nibName: nil, bundle: nil)
        let interactor = SignUpPartnerStep1Interactor()
        let router = SignUpPartnerStep1Router()
        let presenter = SignUpPartnerStep1Presenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
