//
//  ParkingUserDetailInteractor.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingUserDetailInteractor: ParkingUserDetailInteractorInputProtocol {

    weak var presenter: ParkingUserDetailInteractorOutputProtocol?
}
