//
//  ParkingUserDetailPresenter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingUserDetailPresenter: ParkingUserDetailPresenterProtocol, ParkingUserDetailInteractorOutputProtocol {

    weak private var view: ParkingUserDetailViewProtocol?
    var interactor: ParkingUserDetailInteractorInputProtocol?
    private let router: ParkingUserDetailWireframeProtocol

    init(interface: ParkingUserDetailViewProtocol, interactor: ParkingUserDetailInteractorInputProtocol?, router: ParkingUserDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
