//
//  RechargeWalletInteractor.swift
//  EcoPark
//
//  Created Henry on 11/5/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RechargeWalletInteractor: RechargeWalletInteractorInputProtocol {

    weak var presenter: RechargeWalletInteractorOutputProtocol?
}
