//
//  RechargeWalletPresenter.swift
//  EcoPark
//
//  Created Henry on 11/5/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RechargeWalletPresenter: RechargeWalletPresenterProtocol, RechargeWalletInteractorOutputProtocol {

    weak private var view: RechargeWalletViewProtocol?
    var interactor: RechargeWalletInteractorInputProtocol?
    private let router: RechargeWalletWireframeProtocol

    init(interface: RechargeWalletViewProtocol, interactor: RechargeWalletInteractorInputProtocol?, router: RechargeWalletWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
