//
//  RechargeWalletViewController.swift
//  EcoPark
//
//  Created Henry on 11/5/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RechargeWalletViewController: BaseViewController, RechargeWalletViewProtocol {

	var presenter: RechargeWalletPresenterProtocol?
    var isATM : Bool = true
    
    @IBOutlet weak var checkBoxATMCard: AppCheckBox!
    @IBOutlet weak var checkBoxCreditCard: AppCheckBox!
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: "Nạp tiền")
    }
    
    override func setUpViews() {
        super.setUpViews()
        checkBoxATMCard.setTitle(title: "Thẻ ATM nội địa / Internet banking", isCheck: true)
        checkBoxATMCard.delegate = self
        checkBoxCreditCard.setTitle(title: "Thẻ tín dụng / Thẻ ghi nợ", isCheck: false)
        checkBoxCreditCard.delegate = self
    }
}

extension RechargeWalletViewController: AppCheckBoxDelegate {
    func changedStatus(isCheck: Bool) {
        self.isATM = !isATM
        checkBoxATMCard.setStatus(isCheck: isATM)
        checkBoxCreditCard.setStatus(isCheck: !isATM)
        print("isATM = \(isATM)")
    }
}
