//
//  RechargeWalletRouter.swift
//  EcoPark
//
//  Created Henry on 11/5/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RechargeWalletRouter: RechargeWalletWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RechargeWalletViewController(nibName: nil, bundle: nil)
        let interactor = RechargeWalletInteractor()
        let router = RechargeWalletRouter()
        let presenter = RechargeWalletPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
