//
//  SignUpPartnerWaitingViewController.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerWaitingViewController: BaseViewController, SignUpPartnerWaitingViewProtocol {

    @IBOutlet weak var lbWaiting: UILabel!
    
	var presenter: SignUpPartnerWaitingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setTitleNavigation(title: LocalizableKey.MenuSignUpPartner.showLanguage)
        addMenu()
        let attr = NSMutableAttributedString()
        let attr1 = LocalizableKey.parkingWaitingSignUp1.showLanguage.toAttributedString(color: .white, font: AppFont.fontRegular17, isUnderLine: false)
        let attr2 = LocalizableKey.parkingWaitingSignUp2.showLanguage.toAttributedString(color: .white, font: AppFont.fontRegular17, isUnderLine: false)
        let attrEco = "ECOPARKING ".toAttributedString(color: AppColor.color_0_129_255, font: AppFont.fontBold17, isUnderLine: false)
        
        attr.append(attr1)
        attr.append(attrEco)
        attr.append(attr2)
        lbWaiting.attributedText = attr
    }

}
