//
//  SignUpPartnerWaitingViewController.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerWaitingViewController: BaseViewController, SignUpPartnerWaitingViewProtocol {

    @IBOutlet weak var lbWaiting: UILabel!
    
	var presenter: SignUpPartnerWaitingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setTitleNavigation(title: LocalizableKey.MenuSignUpPartner.showLanguage)
        addMenu()
        lbWaiting.text = LocalizableKey.parkingWaitingSignUp.showLanguage
    }

}
