//
//  LoadingViewController.swift
//  EcoPark
//
//  Created Tu DV on 11/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoadingViewController: BaseViewController, LoadingViewProtocol {

    @IBOutlet weak var lbEcoParking: UILabel!
    @IBOutlet weak var lbText1: UILabel!
    @IBOutlet weak var lbText2: UILabel!
    @IBOutlet weak var lbText3: UILabel!
    @IBOutlet weak var lbText4: UILabel!
    @IBOutlet weak var lbText5: UILabel!
    @IBOutlet weak var lbNext: UILabel!
    
	var presenter: LoadingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
            AppRouter.shared.openHomeView()
        }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        hideNavigation()
    }

    private func setupUI() {
        lbText1.text = LocalizableKey.textLoading1.showLanguage
        lbText2.text = LocalizableKey.textLoading2.showLanguage
        lbText3.text = LocalizableKey.textLoading3.showLanguage
        lbText4.text = LocalizableKey.textLoading4.showLanguage
        lbText5.text = LocalizableKey.textLoading5.showLanguage
        
        let attr1 = (LocalizableKey.next1.showLanguage + " >>").toAttributedString(color: AppColor.white, font: AppFont.fontRegular15, isUnderLine: true)
        
        let attr = NSMutableAttributedString()
        attr.append(attr1)
        
        lbNext.attributedText = attr
    }
    
    @IBAction func btnNextTapped() {
        AppRouter.shared.openHomeView()
    }
}
