//
//  LoadingRouter.swift
//  EcoPark
//
//  Created Tu DV on 11/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoadingRouter: LoadingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoadingViewController(nibName: nil, bundle: nil)
        let interactor = LoadingInteractor()
        let router = LoadingRouter()
        let presenter = LoadingPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
