//
//  LoadingProtocols.swift
//  EcoPark
//
//  Created Tu DV on 11/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoadingWireframeProtocol: class {

}
//MARK: Presenter -
protocol LoadingPresenterProtocol: class {

    var interactor: LoadingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol LoadingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol LoadingInteractorInputProtocol: class {

    var presenter: LoadingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol LoadingViewProtocol: class {

    var presenter: LoadingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
