//
//  LoadingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoadingPresenter: LoadingPresenterProtocol, LoadingInteractorOutputProtocol {

    weak private var view: LoadingViewProtocol?
    var interactor: LoadingInteractorInputProtocol?
    private let router: LoadingWireframeProtocol

    init(interface: LoadingViewProtocol, interactor: LoadingInteractorInputProtocol?, router: LoadingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
