//
//  LoadingViewController.swift
//  EcoPark
//
//  Created Tu DV on 11/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoadingViewController: BaseViewController, LoadingViewProtocol {

    @IBOutlet weak var lbNext: UILabel!
    
	var presenter: LoadingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        hideNavigation()
    }

    private func setupUI() {
        let attr1 = "Tiếp >>".toAttributedString(color: AppColor.white, font: AppFont.fontRegular15, isUnderLine: true)
        
        let attr = NSMutableAttributedString()
        attr.append(attr1)
        
        lbNext.attributedText = attr
    }
    
    @IBAction func btnNextTapped() {
        AppRouter.shared.openHomeView()
    }
}
