//
//  CheckOutViewController.swift
//  EcoPark
//
//  Created Henry on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CheckOutViewController: BaseViewController, CheckOutViewProtocol {

	var presenter: CheckOutPresenterProtocol?
    @IBOutlet weak var imgQRCode: UIImageView!
    
    var url: URL?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.backgroundColor = UIColor.black
        
        imgQRCode.sd_setImage(with: url, placeholderImage: AppImage.imgPlaceHolder)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Check out")
        
    }

}
