//
//  CheckOutPresenter.swift
//  EcoPark
//
//  Created Henry on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CheckOutPresenter: CheckOutPresenterProtocol, CheckOutInteractorOutputProtocol {

    weak private var view: CheckOutViewProtocol?
    var interactor: CheckOutInteractorInputProtocol?
    private let router: CheckOutWireframeProtocol

    init(interface: CheckOutViewProtocol, interactor: CheckOutInteractorInputProtocol?, router: CheckOutWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
