//
//  CheckOutRouter.swift
//  EcoPark
//
//  Created Henry on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CheckOutRouter: CheckOutWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(bookingId: String?) -> CheckOutViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CheckOutViewController.initFromNib()
        let interactor = CheckOutInteractor()
        let router = CheckOutRouter()
        let presenter = CheckOutPresenter(interface: view, interactor: interactor, router: router)
        view.bookingId = bookingId
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
