//
//  CheckOutViewController.swift
//  EcoPark
//
//  Created Henry on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CheckOutViewController: BaseViewController, CheckOutViewProtocol {

	var presenter: CheckOutPresenterProtocol?
    @IBOutlet weak var imgQRCode: UIImageView!
    
    var bookingId: String?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.backgroundColor = UIColor.black
        
//
        getBookingDetail(id: bookingId&)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Check out")
        
    }
    
    func getBookingDetail(id: String) {
        ProgressView.shared.show()
        Provider.shared.bookingAPIService.getBookingDetail(bookingId: id, success: { (bookingDetail) in
            ProgressView.shared.hide()
            guard let bookingDetail = bookingDetail else { return }
            self.imgQRCode.sd_setImage(with: bookingDetail.qrUrl, placeholderImage: AppImage.imgPlaceHolder)
        }) { (error) in
            ProgressView.shared.hide()
        }
    }

}
