//
//  HomeFindInteractor.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/26/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeFindInteractor: HomeFindInteractorInputProtocol {

    weak var presenter: HomeFindInteractorOutputProtocol?
}
