//
//  HomeFindRouter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/26/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeFindRouter: HomeFindWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(address: String) -> HomeFindViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeFindViewController.initFromNib()
        let interactor = HomeFindInteractor()
        let router = HomeFindRouter()
        let presenter = HomeFindPresenter(interface: view, interactor: interactor, router: router)
        view.address = address
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
