//
//  HistoryParkingInteractor.swift
//  EcoPark
//
//  Created Steve on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryParkingInteractor: HistoryParkingInteractorInputProtocol {

    weak var presenter: HistoryParkingInteractorOutputProtocol?
}
