//
//  ProfileInteractor.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileInteractor: ProfileInteractorInputProtocol {

    weak var presenter: ProfileInteractorOutputProtocol?
}
