//
//  QRScannerInteractor.swift
//  EcoPark
//
//  Created Henry on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QRScannerInteractor: QRScannerInteractorInputProtocol {

    weak var presenter: QRScannerInteractorOutputProtocol?
}
