//
//  QRScannerViewController.swift
//  EcoPark
//
//  Created Henry on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QRScannerViewController: BaseViewController, QRScannerViewProtocol {

	var presenter: QRScannerPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        PopUpHelper.shared.showRating(width: popUpwidth, completionCancel: {
            //
        }) { (rating) in
            print(rating)
        }
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Scan QR & Check in")
    }

}
