//
//  QRScannerRouter.swift
//  EcoPark
//
//  Created Henry on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QRScannerRouter: QRScannerWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> QRScannerViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QRScannerViewController.initFromNib()
        let interactor = QRScannerInteractor()
        let router = QRScannerRouter()
        let presenter = QRScannerPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
