//
//  QRScannerProtocols.swift
//  EcoPark
//
//  Created Henry on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QRScannerWireframeProtocol: class {

}
//MARK: Presenter -
protocol QRScannerPresenterProtocol: class {

    var interactor: QRScannerInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol QRScannerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol QRScannerInteractorInputProtocol: class {

    var presenter: QRScannerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol QRScannerViewProtocol: class {

    var presenter: QRScannerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
