//
//  QRScannerPresenter.swift
//  EcoPark
//
//  Created Henry on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QRScannerPresenter: QRScannerPresenterProtocol, QRScannerInteractorOutputProtocol {

    weak private var view: QRScannerViewProtocol?
    var interactor: QRScannerInteractorInputProtocol?
    private let router: QRScannerWireframeProtocol

    init(interface: QRScannerViewProtocol, interactor: QRScannerInteractorInputProtocol?, router: QRScannerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
