//
//  DetailTransactionCustomerProtocols.swift
//  EcoPark
//
//  Created Steve on 11/9/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailTransactionCustomerWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailTransactionCustomerPresenterProtocol: class {

    var interactor: DetailTransactionCustomerInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DetailTransactionCustomerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DetailTransactionCustomerInteractorInputProtocol: class {

    var presenter: DetailTransactionCustomerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DetailTransactionCustomerViewProtocol: class {

    var presenter: DetailTransactionCustomerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
