//
//  DetailTransactionCustomerPresenter.swift
//  EcoPark
//
//  Created Steve on 11/9/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailTransactionCustomerPresenter: DetailTransactionCustomerPresenterProtocol, DetailTransactionCustomerInteractorOutputProtocol {

    weak private var view: DetailTransactionCustomerViewProtocol?
    var interactor: DetailTransactionCustomerInteractorInputProtocol?
    private let router: DetailTransactionCustomerWireframeProtocol

    init(interface: DetailTransactionCustomerViewProtocol, interactor: DetailTransactionCustomerInteractorInputProtocol?, router: DetailTransactionCustomerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
