//
//  HistoryPartnerHoldingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerHoldingPresenter: HistoryPartnerHoldingPresenterProtocol, HistoryPartnerHoldingInteractorOutputProtocol {

    weak private var view: HistoryPartnerHoldingViewProtocol?
    var interactor: HistoryPartnerHoldingInteractorInputProtocol?
    private let router: HistoryPartnerHoldingWireframeProtocol

    init(interface: HistoryPartnerHoldingViewProtocol, interactor: HistoryPartnerHoldingInteractorInputProtocol?, router: HistoryPartnerHoldingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
