//
//  HistoryPartnerHoldingProtocols.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryPartnerHoldingWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPartnerHoldingPresenterProtocol: class {

    var interactor: HistoryPartnerHoldingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol HistoryPartnerHoldingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HistoryPartnerHoldingInteractorInputProtocol: class {

    var presenter: HistoryPartnerHoldingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryPartnerHoldingViewProtocol: class {

    var presenter: HistoryPartnerHoldingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
