//
//  HistoryPartnerHoldingInteractor.swift
//  EcoPark
//
//  Created Tu DV on 11/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerHoldingInteractor: HistoryPartnerHoldingInteractorInputProtocol {

    weak var presenter: HistoryPartnerHoldingInteractorOutputProtocol?
}
