//
//  HistoryPartnerDetailCheckinRouter.swift
//  EcoPark
//
//  Created Tu DV on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailCheckinRouter: HistoryPartnerDetailCheckinWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(parkingID: String, bookingID: String) -> HistoryPartnerDetailCheckinViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HistoryPartnerDetailCheckinViewController(nibName: nil, bundle: nil)
        let interactor = HistoryPartnerDetailCheckinInteractor()
        let router = HistoryPartnerDetailCheckinRouter()
        let presenter = HistoryPartnerDetailCheckinPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        view.parkingID = parkingID
        view.bookingID = bookingID
        return view
    }
}
