//
//  SignUpPartnerStep2Router.swift
//  EnglishApp
//
//  Created Tu DV on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep2Router: SignUpPartnerStep2WireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignUpPartnerStep2ViewController(nibName: nil, bundle: nil)
        let interactor = SignUpPartnerStep2Interactor()
        let router = SignUpPartnerStep2Router()
        let presenter = SignUpPartnerStep2Presenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
