//
//  BookingInfoInteractor.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BookingInfoInteractor: BookingInfoInteractorInputProtocol {

    weak var presenter: BookingInfoInteractorOutputProtocol?
}
