//
//  BookingInfoProtocols.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BookingInfoWireframeProtocol: class {

}
//MARK: Presenter -
protocol BookingInfoPresenterProtocol: class {

    var interactor: BookingInfoInteractorInputProtocol? { get set }
    func getParkingInfo(id: String)
    func getVehicleType()
    func booking(time: String, parkId: String, vehicleId: String, plate: String, moneyPaid: String)
}

//MARK: Interactor -
protocol BookingInfoInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetError(error: APIError)
    func didGetInfo(info: ParkingInfoEntity)
    func didGetVehicleType(listVehicle: [VehicleTypeEntity])
    func didBooking()
}

protocol BookingInfoInteractorInputProtocol: class {

    var presenter: BookingInfoInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getParkingInfo(id: String)
    func getVehicleType()
    func booking(time: String, parkId: String, vehicleId: String, plate: String, moneyPaid: String)
}

//MARK: View -
protocol BookingInfoViewProtocol: class {

    var presenter: BookingInfoPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetError(error: APIError)
    func didGetInfo(info: ParkingInfoEntity)
    func didGetVehicleType(listVehicle: [VehicleTypeEntity])
    func didBooking()
}
