//
//  BookingInfoPresenter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BookingInfoPresenter: BookingInfoPresenterProtocol, BookingInfoInteractorOutputProtocol {

    weak private var view: BookingInfoViewProtocol?
    var interactor: BookingInfoInteractorInputProtocol?
    private let router: BookingInfoWireframeProtocol

    init(interface: BookingInfoViewProtocol, interactor: BookingInfoInteractorInputProtocol?, router: BookingInfoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
