//
//  BookingInfoViewController.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BookingInfoViewController: BaseViewController, BookingInfoViewProtocol {

	var presenter: BookingInfoPresenterProtocol?
    var parking: ParkingEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Đặt giữ chỗ")
    }
    
    @IBAction func btnBookingTapped() {
        let pop = BookingPopUp()
        pop.showPopUp(address: "Address", message: "10", completionDirection: {
            print("Direction")
        }) {
            print("Detail")
        }
    }

}
