//
//  BookingInfoInteractor.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BookingInfoInteractor: BookingInfoInteractorInputProtocol {

    weak var presenter: BookingInfoInteractorOutputProtocol?
    
    // MARK: Get Park Info
    func getParkingInfo(id: String) {
        Provider.shared.parkingAPIService.getParkingInfo(id: id, success: { (info) in
            guard let info = info else { return }
            self.presenter?.didGetInfo(info: info)
        }) { (error) in
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
    
    // MARK: Get vehicel type
    func getVehicleType() {
        Provider.shared.parkingAPIService.getListVehicle(success: { (list) in
            self.presenter?.didGetVehicleType(listVehicle: list)
        }) { (error) in
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
}
