//
//  BookingInfoPresenter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BookingInfoPresenter: BookingInfoPresenterProtocol, BookingInfoInteractorOutputProtocol {

    weak private var view: BookingInfoViewProtocol?
    var interactor: BookingInfoInteractorInputProtocol?
    private let router: BookingInfoWireframeProtocol

    init(interface: BookingInfoViewProtocol, interactor: BookingInfoInteractorInputProtocol?, router: BookingInfoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    // MARK: Get vehicel type
    func getVehicleType() {
        self.interactor?.getVehicleType()
    }
    func didGetVehicleType(listVehicle: [VehicleTypeEntity]) {
        self.view?.didGetVehicleType(listVehicle: listVehicle)
    }
    
    // MARK: Get Park Info
    func getParkingInfo(id: String) {
        self.interactor?.getParkingInfo(id: id)
    }
    func didGetInfo(info: ParkingInfoEntity) {
        self.view?.didGetInfo(info: info)
    }
    
    // MARK: Get Error
    func didGetError(error: APIError) {
        self.view?.didGetError(error: error)
    }

}
