//
//  SignUpPartnerWaitingPresenter.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerWaitingPresenter: SignUpPartnerWaitingPresenterProtocol, SignUpPartnerWaitingInteractorOutputProtocol {

    weak private var view: SignUpPartnerWaitingViewProtocol?
    var interactor: SignUpPartnerWaitingInteractorInputProtocol?
    private let router: SignUpPartnerWaitingWireframeProtocol

    init(interface: SignUpPartnerWaitingViewProtocol, interactor: SignUpPartnerWaitingInteractorInputProtocol?, router: SignUpPartnerWaitingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
