//
//  SignUpPartnerWaitingProtocols.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpPartnerWaitingWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPartnerWaitingPresenterProtocol: class {

    var interactor: SignUpPartnerWaitingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SignUpPartnerWaitingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignUpPartnerWaitingInteractorInputProtocol: class {

    var presenter: SignUpPartnerWaitingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignUpPartnerWaitingViewProtocol: class {

    var presenter: SignUpPartnerWaitingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
