//
//  SignUpPartnerStep2Interactor.swift
//  EnglishApp
//
//  Created Tu DV on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep2Interactor: SignUpPartnerStep2InteractorInputProtocol {

    weak var presenter: SignUpPartnerStep2InteractorOutputProtocol?
}
