//
//  SignUpPartnerStep2Protocols.swift
//  EnglishApp
//
//  Created Tu DV on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
//MARK: Wireframe -
protocol SignUpPartnerStep2WireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPartnerStep2PresenterProtocol: class {

    var interactor: SignUpPartnerStep2InteractorInputProtocol? { get set }
    func getListParkingType()
    func uploadImageFront(image: UIImage)
    func uploadImageBackside(image: UIImage)
    func getNumberHours()
}

//MARK: Interactor -
protocol SignUpPartnerStep2InteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignUpPartnerStep2InteractorInputProtocol: class {

    var presenter: SignUpPartnerStep2InteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignUpPartnerStep2ViewProtocol: class {

    var presenter: SignUpPartnerStep2PresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetListParkingType(listParkingType: [ParkingTypeEntity])
    
    func didUploadImageFront(photo: String?)
    func didUploadImageBackside(photo: String?)
    func didGetNumberHours(numberHours: String?)
}
