//
//  ImageParkingInteractor.swift
//  EcoPark
//
//  Created Tu DV on 11/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ImageParkingInteractor: ImageParkingInteractorInputProtocol {

    weak var presenter: ImageParkingInteractorOutputProtocol?
}
