//
//  ImageParkingViewController.swift
//  EcoPark
//
//  Created Tu DV on 11/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SDWebImage

class ImageParkingViewController: BaseViewController, ImageParkingViewProtocol {

    @IBOutlet weak var cvPhoto: AppCollectionPhoto!
    @IBOutlet weak var btnBack: UIButton!
    @IBOutlet weak var btnSave: UIButton!
    @IBOutlet weak var lbTitle: UILabel!
    
    var listImage: [String] = []
    
	var presenter: ImageParkingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }

    @IBAction func btnReturnTapped() {
        
    }
    
    @IBAction func btnSaveTapped() {
        
    }
}
