//
//  ImageParkingProtocols.swift
//  EcoPark
//
//  Created Tu DV on 11/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ImageParkingWireframeProtocol: class {

}
//MARK: Presenter -
protocol ImageParkingPresenterProtocol: class {

    var interactor: ImageParkingInteractorInputProtocol? { get set }
    func uploadImageParking(parkingID: String, parkingImage: [String])
}

//MARK: Interactor -
protocol ImageParkingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ImageParkingInteractorInputProtocol: class {

    var presenter: ImageParkingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ImageParkingViewProtocol: class {

    var presenter: ImageParkingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
   func didUploadImageParking()
}
