//
//  ImageParkingViewController.swift
//  EcoPark
//
//  Created Tu DV on 11/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SDWebImage

class ImageParkingViewController: BaseViewController, ImageParkingViewProtocol {

    @IBOutlet weak var vPhoto: AppCollectionPhoto!
    @IBOutlet weak var btnBack: UIButton!
    @IBOutlet weak var btnSave: UIButton!
    @IBOutlet weak var lbTitle: UILabel!
    
    var listImage: [String] = []
    
	var presenter: ImageParkingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setTitleNavigation(title: "Cập nhật hình ảnh bãi xe")
        let images = listImage.map { (string) -> AppPhoto in
            return AppPhoto(status: AppPhotoStatus.uploaded, image: nil, url: string)
        }
        vPhoto.listImage = images
    }

    @IBAction func btnReturnTapped() {
        self.pop()
    }
    
    @IBAction func btnSaveTapped() {
        let listImage = vPhoto.listImage.map({ $0.url&})
        presenter?.uploadImageParking(parkingID: "2", parkingImage: listImage)
    }
    
    func didUploadImageParking() {
        
    }
    
}
