//
//  ImageParkingPresenter.swift
//  EcoPark
//
//  Created Tu DV on 11/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ImageParkingPresenter: ImageParkingPresenterProtocol, ImageParkingInteractorOutputProtocol {

    weak private var view: ImageParkingViewProtocol?
    var interactor: ImageParkingInteractorInputProtocol?
    private let router: ImageParkingWireframeProtocol

    init(interface: ImageParkingViewProtocol, interactor: ImageParkingInteractorInputProtocol?, router: ImageParkingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func uploadImageParking(parkingID: String, parkingImage: [String]) {
        Provider.shared.parkingAPIService.uploadImageParking(parkingID: parkingID, ParkingImage: parkingImage, success: { (images) in
            self.view?.didUploadImageParking()
        }) { (error) in
            
        }
    }
}
