//
//  HistoryPartnerDetailCheckAgainProtocols.swift
//  EcoPark
//
//  Created Tu DV on 12/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryPartnerDetailCheckAgainWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPartnerDetailCheckAgainPresenterProtocol: class {

    var interactor: HistoryPartnerDetailCheckAgainInteractorInputProtocol? { get set }
    func getHistoryParkingDetailCheckIn(parkingID: String, bookingID: String)
    func checkoutParking(bookingID: String, code: String, licensePlates: String)
    func changeStatusCheckout(bookingID: String)
}

//MARK: Interactor -
protocol HistoryPartnerDetailCheckAgainInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HistoryPartnerDetailCheckAgainInteractorInputProtocol: class {

    var presenter: HistoryPartnerDetailCheckAgainInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryPartnerDetailCheckAgainViewProtocol: class {

    var presenter: HistoryPartnerDetailCheckAgainPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didCheckout(historyParkingDetail: HistoryBookingParkingResponse?)
    func didChangeStatusCheckout(historyCheckout: BookingDetailEntity?)
    func didGetData(historyParkingDetail: HistoryBookingParkingResponse?)
}
