//
//  HistoryPartnerDetailCheckAgainRouter.swift
//  EcoPark
//
//  Created Tu DV on 12/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailCheckAgainRouter: HistoryPartnerDetailCheckAgainWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(parkingID: String, bookingID: String) -> HistoryPartnerDetailCheckAgainViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HistoryPartnerDetailCheckAgainViewController(nibName: nil, bundle: nil)
        let interactor = HistoryPartnerDetailCheckAgainInteractor()
        let router = HistoryPartnerDetailCheckAgainRouter()
        let presenter = HistoryPartnerDetailCheckAgainPresenter(interface: view, interactor: interactor, router: router)

        view.parkingID = parkingID
        view.bookingID = bookingID
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
