//
//  HistoryPartnerDetailCheckAgainInteractor.swift
//  EcoPark
//
//  Created Tu DV on 12/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPartnerDetailCheckAgainInteractor: HistoryPartnerDetailCheckAgainInteractorInputProtocol {

    weak var presenter: HistoryPartnerDetailCheckAgainInteractorOutputProtocol?
}
