//
//  SystemNotificationInteractor.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SystemNotificationInteractor: SystemNotificationInteractorInputProtocol {

    weak var presenter: SystemNotificationInteractorOutputProtocol?
}
