//
//  SystemNotificationPresenter.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SystemNotificationPresenter: SystemNotificationPresenterProtocol, SystemNotificationInteractorOutputProtocol {

    weak private var view: SystemNotificationViewProtocol?
    var interactor: SystemNotificationInteractorInputProtocol?
    private let router: SystemNotificationWireframeProtocol

    init(interface: SystemNotificationViewProtocol, interactor: SystemNotificationInteractorInputProtocol?, router: SystemNotificationWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
