//
//  SignUpPartnerStep3ViewController.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep3ViewController: BaseViewController, SignUpPartnerStep3ViewProtocol {

    @IBOutlet weak var vStep: PartnerStepView!
    @IBOutlet weak var lbUtility: UILabel!
    @IBOutlet weak var lbImage: UILabel!
    @IBOutlet weak var lbSubImage: UILabel!
    @IBOutlet weak var cvUtility: UICollectionView!
    
	var presenter: SignUpPartnerStep3PresenterProtocol?

    var listUtility: [String] = []
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        listUtility = ["ic_roof_on", "ic_carwash_off", "ic_repair_on", "ic_rent_on", "ic_supermarket_off", "ic_atm_on", "ic_hotel_off", "ic_coffee_on"]
        setupUI()
        configCollectionView()
    }
    
    private func setupUI() {
        vStep.setStep3()
        lbUtility.text = LocalizableKey.utilityOther.showLanguage.uppercased()
        lbImage.text = LocalizableKey.parkingImage.showLanguage.uppercased()
        lbSubImage.text = LocalizableKey.parkingSubImage.showLanguage
    }
}

extension SignUpPartnerStep3ViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func configCollectionView() {
        cvUtility.registerXibCell(UtilityCell.self)
        
        cvUtility.dataSource = self
        cvUtility.delegate = self
        
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return listUtility.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueCell(UtilityCell.self, indexPath: indexPath)
        cell.imgItem.image = UIImage(named: listUtility[indexPath.item])
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        return CGSize(width: 90, height: 60)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 8
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        return 2
    }
}
