//
//  SignUpPartnerStep3Presenter.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPartnerStep3Presenter: SignUpPartnerStep3PresenterProtocol, SignUpPartnerStep3InteractorOutputProtocol {

    weak private var view: SignUpPartnerStep3ViewProtocol?
    var interactor: SignUpPartnerStep3InteractorInputProtocol?
    private let router: SignUpPartnerStep3WireframeProtocol

    init(interface: SignUpPartnerStep3ViewProtocol, interactor: SignUpPartnerStep3InteractorInputProtocol?, router: SignUpPartnerStep3WireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
