//
//  ParkingUserDetailViewController.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingUserDetailViewController: BaseViewController, ParkingUserDetailViewProtocol {

	var presenter: ParkingUserDetailPresenterProtocol?
    @IBOutlet weak var vAppImageSlide: AppImageSlide!
    
    var parking: ParkingEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpViews() {
        super.setUpViews()
        
        vAppImageSlide.listItem = ["https://tranhtuong24h.com/profiles/tranhtuong24hcom/uploads/attach/post/images/phong-canh-chau-au-04.jpg", "https://tranhtuong24h.com/profiles/tranhtuong24hcom/uploads/attach/post/images/phong-canh-chau-au-04.jpg", "https://tranhtuong24h.com/profiles/tranhtuong24hcom/uploads/attach/post/images/phong-canh-chau-au-04.jpg"]
        
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Chi tiết bãi giữ xe")
    }
    
    @IBAction func btnBookingTapped() {
        let vc = BookingInfoRouter.createModule(parking: self.parking)
        self.push(controller: vc)
    }
}
