//
//  ParkingUserDetailViewController.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingUserDetailViewController: BaseViewController, ParkingUserDetailViewProtocol {

    @IBOutlet weak var vAppImageSlide: AppImageSlide!
    @IBOutlet weak var lbName: UILabel!
    @IBOutlet weak var ratingBar: AppRatingView!
    @IBOutlet weak var lbTitleTime: UILabel!
    @IBOutlet weak var lbTime: UILabel!
    @IBOutlet weak var lbTitleType: UILabel!
    @IBOutlet weak var lbType: UILabel!
    @IBOutlet weak var lbTitleEmptyPlace: UILabel!
    @IBOutlet weak var lbEmptyPlace: UILabel!
    @IBOutlet weak var lbTitlePriceOneHour: UILabel!
    @IBOutlet weak var lbPriceOneHour: UILabel!
    @IBOutlet weak var lbTitlePriceEightHour: UILabel!
    @IBOutlet weak var lbPriceEightHour: UILabel!
    @IBOutlet weak var lbAddress: UILabel!
    @IBOutlet weak var btnContact: UIButton!
    @IBOutlet weak var btnDirect: UIButton!
    @IBOutlet weak var cltMaterial: UtilityView!
    @IBOutlet weak var btnBookNow: UIButton!
    
	var presenter: ParkingUserDetailPresenterProtocol?
    var parking: ParkingEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        getParkingDetail()
    }
        
    override func setUpViews() {
        super.setUpViews()
        
        ratingBar.isUserInteractionEnabled = false
        lbTitleTime.text = LocalizableKey.parkingTime.showLanguage
        lbTitleType.text = LocalizableKey.titleType.showLanguage
        lbTitleEmptyPlace.text = LocalizableKey.titlePlace.showLanguage
        lbTitlePriceOneHour.text = LocalizableKey.titlePriceOne.showLanguage
        lbTitlePriceEightHour.text = LocalizableKey.titlePriceEight.showLanguage
        
        btnContact.setTitle(LocalizableKey.titleContactMe.showLanguage, for: .normal)
        btnDirect.setTitle(LocalizableKey.titleDirection.showLanguage, for: .normal)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.titleParkDetail.showLanguage)
    }
    
    @IBAction func btnBookingTapped() {
        let vc = BookingInfoRouter.createModule(parking: self.parking)
        self.push(controller: vc)
    }
    
    @IBAction func btnContactTapped() {
        // Code here
    }
    
    @IBAction func btnDirectTapped() {
        // Code here
    }
    
    func displayData(info: ParkingInfoEntity) {
        if let listImage = info.img?.map({ $0.imageURL }){
            vAppImageSlide.listItem = listImage as [Any]
        }
        lbName.text = info.name&
        ratingBar.setStar(number: info.rating ?? 0)
        if let timeStart = info.time_start?.toString(dateFormat: .HHmm),
            let timeEnd = info.time_end?.toString(dateFormat: .HHmm) {
            lbTime.text = timeStart + " - " + timeEnd
        }
        lbType.text = info.parking_type
        lbEmptyPlace.text = "xxx"
        if let price = info.price {
            lbPriceOneHour.text = price.toCurrency
        }
        if let packagePrice = info.package_price {
            lbPriceEightHour.text = packagePrice.toCurrency
        }
        
        lbAddress.text = info.address
        cltMaterial.setMaterial(listMaterial: [.roof, .repair, .rent, .atm])
    }
    
    // MARK: Get error
    func didGetError(error: APIError) {
        printError(message: error.message)
    }
    
    // MARK: Get Park Info
    func getParkingDetail() {
        if let id = parking?.parking_id {
            self.presenter?.getParkingInfo(id: id)
        }
    }
    func didGetInfo(info: ParkingInfoEntity) {
        displayData(info: info)
    }
}

