//
//  ParkingUserDetailRouter.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingUserDetailRouter: ParkingUserDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(parking: ParkingEntity?) -> ParkingUserDetailViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ParkingUserDetailViewController.initFromNib()
        let interactor = ParkingUserDetailInteractor()
        let router = ParkingUserDetailRouter()
        let presenter = ParkingUserDetailPresenter(interface: view, interactor: interactor, router: router)

        view.parking = parking
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
