//
//  ParkingUserDetailProtocols.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ParkingUserDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol ParkingUserDetailPresenterProtocol: class {

    var interactor: ParkingUserDetailInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ParkingUserDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ParkingUserDetailInteractorInputProtocol: class {

    var presenter: ParkingUserDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ParkingUserDetailViewProtocol: class {

    var presenter: ParkingUserDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
