//
//  DetailParkingPresenter.swift
//  EcoPark
//
//  Created Steve on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailParkingPresenter: DetailParkingPresenterProtocol, DetailParkingInteractorOutputProtocol {

    weak private var view: DetailParkingViewProtocol?
    var interactor: DetailParkingInteractorInputProtocol?
    private let router: DetailParkingWireframeProtocol

    init(interface: DetailParkingViewProtocol, interactor: DetailParkingInteractorInputProtocol?, router: DetailParkingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
