//
//  DetailParkingInteractor.swift
//  EcoPark
//
//  Created Steve on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailParkingInteractor: DetailParkingInteractorInputProtocol {

    weak var presenter: DetailParkingInteractorOutputProtocol?
    
    func getBookingDetail(id: String) {
        ProgressView.shared.show()
        Provider.shared.bookingAPIService.getBookingDetail(bookingId: id, success: { (info) in
            ProgressView.shared.hide()
            guard let info = info else { return }
            self.presenter?.didGetBookingDetail(info: info)
        }) { (error) in
            ProgressView.shared.hide()
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
    
    func cancelReservation(id: String) {
        ProgressView.shared.show()
        Provider.shared.bookingAPIService.cancelReservation(bookingId: id, success: { (info) in
            ProgressView.shared.hide()
            self.presenter?.didCancelReservation()
        }) { (error) in
            ProgressView.shared.hide()
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
    
    func extendReservation(id: String) {
        ProgressView.shared.show()
        Provider.shared.bookingAPIService.cancelReservation(bookingId: id, success: { (info) in
            ProgressView.shared.hide()
            guard let info = info else { return }
            self.presenter?.didExtendReservation(info: info)
        }) { (error) in
            ProgressView.shared.hide()
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
    
}
