//
//  DetailParkingInteractor.swift
//  EcoPark
//
//  Created Steve on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailParkingInteractor: DetailParkingInteractorInputProtocol {

    weak var presenter: DetailParkingInteractorOutputProtocol?
}
