//
//  DetailParkingProtocols.swift
//  EcoPark
//
//  Created Steve on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailParkingWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailParkingPresenterProtocol: class {

    var interactor: DetailParkingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DetailParkingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DetailParkingInteractorInputProtocol: class {

    var presenter: DetailParkingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DetailParkingViewProtocol: class {

    var presenter: DetailParkingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
