//
//  ProfileProtocols.swift
//  EnglishApp
//
//  Created Tu DV on 10/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol ProfileWireframeProtocol: class {

}
//MARK: Presenter -
protocol ProfilePresenterProtocol: class {

    var interactor: ProfileInteractorInputProtocol? { get set }
    func updateAvatar(image: UIImage)
}

//MARK: Interactor -
protocol ProfileInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
   
}

protocol ProfileInteractorInputProtocol: class {

    var presenter: ProfileInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
     
}

//MARK: View -
protocol ProfileViewProtocol: class {

    var presenter: ProfilePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
     func didUpdateAvatar()
}
