//
//  HomeViewController.swift
//  EnglishApp
//
//  Created Ngoc Duong on 10/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: BaseViewController, HomeViewProtocol {

	var presenter: HomePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addButtonToNavigation(image: AppImage.imgMenu, style: .left, action: nil)
        addButtonToNavigation(image: AppImage.iconCheckout, style: .right, action: nil)
        setTitleBoldLeftNavigation(title: "EcoParking", action: nil)
    }

}
