//
//  NotificationDetailPresenter.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationDetailPresenter: NotificationDetailPresenterProtocol, NotificationDetailInteractorOutputProtocol {

    weak private var view: NotificationDetailViewProtocol?
    var interactor: NotificationDetailInteractorInputProtocol?
    private let router: NotificationDetailWireframeProtocol

    init(interface: NotificationDetailViewProtocol, interactor: NotificationDetailInteractorInputProtocol?, router: NotificationDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getNotificationDetail(notificationID: Int) {
        Provider.shared.notificationAPIService.getNotificationDetail(id: notificationID, success: { (notificationDetail) in
            self.view?.didGetNotificationDetail(notificationDetail: notificationDetail)
        }) { (error) in
            
        }
    }
}
