//
//  NotificationDetailViewController.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class NotificationDetailViewController: BaseViewController, NotificationDetailViewProtocol {

	var presenter: NotificationDetailPresenterProtocol?
    
    @IBOutlet weak var webView: WKWebView!

    var notificationID: Int? = 0
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        presenter?.getNotificationDetail(notificationID: notificationID*)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Chi tiết thông báo")
    }

    func didGetNotificationDetail(notificationDetail: NotificationEntity?) {
        
    }
}
