//
//  NotificationDetailViewController.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class NotificationDetailViewController: BaseViewController, NotificationDetailViewProtocol {

	var presenter: NotificationDetailPresenterProtocol?
    
    @IBOutlet weak var webView: WKWebView!

    var notificationID = 0
    var content: String? = ""
    
    
	override func viewDidLoad() {
        super.viewDidLoad()
//        webView.loadHTMLString(content ?? "", baseURL: nil)
        let mainUrl = "_api/webview/get_notification_detail/\(notificationID)"
       
        guard let url = URL(string: BASE_URL + "\(mainUrl)") else { return }
        var request = URLRequest(url: url)
        let code = LanguageHelper.currentAppleLanguage()
        request.setValue("\(code)", forHTTPHeaderField: "Language")
        webView.load(request)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        presenter?.getNotificationDetail(notificationID: notificationID*)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.NotificationDetail.showLanguage)
    }

    func didGetNotificationDetail(notificationDetail: NotificationEntity?) {
        
    }
}
