//
//  NotificationDetailRouter.swift
//  EcoPark
//
//  Created Henry on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationDetailRouter: NotificationDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(notificationID: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = NotificationDetailViewController(nibName: nil, bundle: nil)
        let interactor = NotificationDetailInteractor()
        let router = NotificationDetailRouter()
        let presenter = NotificationDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.notificationID = notificationID
        return view
    }
}
