//
//  WalletInteractor.swift
//  EcoPark
//
//  Created Ngoc Duong on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WalletInteractor: WalletInteractorInputProtocol {

    weak var presenter: WalletInteractorOutputProtocol?
    
    func getWallet() {
        Provider.shared.userAPIService.getWallet(success: { (wallet) in
            guard let wallet = wallet else { return }
            self.presenter?.didGetWallet(wallet: wallet)
        }) { (error) in
            guard let error = error else { return }
            self.presenter?.didGetError(error: error)
        }
    }
}
