//
//  WalletProtocols.swift
//  EcoPark
//
//  Created Ngoc Duong on 11/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WalletWireframeProtocol: class {

}
//MARK: Presenter -
protocol WalletPresenterProtocol: class {

    var interactor: WalletInteractorInputProtocol? { get set }
    func getWallet()
    func didGetWallet(wallet: WalletEntity)
    var canLoadMore: Bool { get }
    var listWalletHistory: [HistoryWallet] { get set }
    func getWalletHistory(startDate: String, toDate: String, showLoading: Bool)
    func didGetWalletHistory(listLog: [HistoryWallet])
}

//MARK: Interactor -
protocol WalletInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetWallet(wallet: WalletEntity)
    func didGetWalletHistory(listLog: [HistoryWallet])
    func didGetError(error: APIError)
}

protocol WalletInteractorInputProtocol: class {

    var presenter: WalletInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getWallet()
    func getWalletHistory(startDate: String, toDate: String, offset: Int, showLoading: Bool)
}

//MARK: View -
protocol WalletViewProtocol: class {

    var presenter: WalletPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetError(error: APIError)
    func didGetWallet(wallet: WalletEntity)
    func didGetWalletHistory(listLog: [HistoryWallet])
}
