//
//  ParkingInfoRouter.swift
//  EnglishApp
//
//  Created Tu DV on 10/31/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ParkingInfoRouter: ParkingInfoWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ParkingInfoViewController(nibName: nil, bundle: nil)
        let interactor = ParkingInfoInteractor()
        let router = ParkingInfoRouter()
        let presenter = ParkingInfoPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
