//
//  DoingViewController.swift
//  EcoPark
//
//  Created Steve on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DoingViewController: ListManagerVC, DoingViewProtocol {

	var presenter: DoingPresenterProtocol?

    override func setUpViews() {
        super.setUpViews()
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.initLoadData(data: Array(repeating: 1, count: 10))
        }
        self.view.backgroundColor = .clear
    }

    override func registerTableView() {
        super.registerTableView()
        self.tableView.registerXibFile(DoingCell.self)
    }
    
    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = self.tableView.dequeue(DoingCell.self, for: indexPath)
        return cell
    }
}
