//
//  DoingPresenter.swift
//  EcoPark
//
//  Created Steve on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DoingPresenter: DoingPresenterProtocol, DoingInteractorOutputProtocol {

    weak private var view: DoingViewProtocol?
    var interactor: DoingInteractorInputProtocol?
    private let router: DoingWireframeProtocol

    init(interface: DoingViewProtocol, interactor: DoingInteractorInputProtocol?, router: DoingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
