//
//  DoingProtocols.swift
//  EcoPark
//
//  Created Steve on 11/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DoingWireframeProtocol: class {

}
//MARK: Presenter -
protocol DoingPresenterProtocol: class {

    var interactor: DoingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DoingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DoingInteractorInputProtocol: class {

    var presenter: DoingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DoingViewProtocol: class {

    var presenter: DoingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
